// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/companies": {
    params: {};
  };
  "/companies/new": {
    params: {};
  };
  "/companies/:id": {
    params: {
      "id": string;
    };
  };
  "/companies/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/companies/:id/customers": {
    params: {
      "id": string;
    };
  };
  "/companies/:id/leistungen": {
    params: {
      "id": string;
    };
  };
  "/companies/:id/invoices": {
    params: {
      "id": string;
    };
  };
  "/companies/:id/invoices/new": {
    params: {
      "id": string;
    };
  };
  "/companies/:id/invoices/:invoiceId": {
    params: {
      "id": string;
      "invoiceId": string;
    };
  };
  "/companies/:id/invoices/:invoiceId/edit": {
    params: {
      "id": string;
      "invoiceId": string;
    };
  };
  "/companies/:id/reports": {
    params: {
      "id": string;
    };
  };
  "/archiv": {
    params: {};
  };
  "/settings/password": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/users/new": {
    params: {};
  };
  "/admin/users/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/logs": {
    params: {};
  };
  "/api/companies": {
    params: {};
  };
  "/api/companies/:id": {
    params: {
      "id": string;
    };
  };
  "/api/companies/:id/customers": {
    params: {
      "id": string;
    };
  };
  "/api/companies/:id/invoices": {
    params: {
      "id": string;
    };
  };
  "/api/customers": {
    params: {};
  };
  "/api/customers/:id": {
    params: {
      "id": string;
    };
  };
  "/api/services": {
    params: {};
  };
  "/api/services/:id": {
    params: {
      "id": string;
    };
  };
  "/api/invoices": {
    params: {};
  };
  "/api/invoices/:id": {
    params: {
      "id": string;
    };
  };
  "/api/invoices/:id/pdf": {
    params: {
      "id": string;
    };
  };
  "/api/invoices/:id/xml": {
    params: {
      "id": string;
    };
  };
  "/api/reports": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/companies" | "/companies/new" | "/companies/:id" | "/companies/:id/edit" | "/companies/:id/customers" | "/companies/:id/leistungen" | "/companies/:id/invoices" | "/companies/:id/invoices/new" | "/companies/:id/invoices/:invoiceId" | "/companies/:id/invoices/:invoiceId/edit" | "/companies/:id/reports" | "/archiv" | "/settings/password" | "/admin/users" | "/admin/users/new" | "/admin/users/:id" | "/admin/logs" | "/api/companies" | "/api/companies/:id" | "/api/companies/:id/customers" | "/api/companies/:id/invoices" | "/api/customers" | "/api/customers/:id" | "/api/services" | "/api/services/:id" | "/api/invoices" | "/api/invoices/:id" | "/api/invoices/:id/pdf" | "/api/invoices/:id/xml" | "/api/reports";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.ts": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/dashboard-layout.tsx": {
    id: "routes/dashboard-layout";
    page: "/" | "/companies" | "/companies/new" | "/companies/:id" | "/companies/:id/edit" | "/companies/:id/customers" | "/companies/:id/leistungen" | "/companies/:id/invoices" | "/companies/:id/invoices/new" | "/companies/:id/invoices/:invoiceId" | "/companies/:id/invoices/:invoiceId/edit" | "/companies/:id/reports" | "/archiv" | "/settings/password";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/companies.tsx": {
    id: "routes/companies";
    page: "/companies";
  };
  "routes/companies.new.tsx": {
    id: "routes/companies.new";
    page: "/companies/new";
  };
  "routes/companies.$id.tsx": {
    id: "routes/companies.$id";
    page: "/companies/:id";
  };
  "routes/companies.$id.edit.tsx": {
    id: "routes/companies.$id.edit";
    page: "/companies/:id/edit";
  };
  "routes/companies.$id.customers.tsx": {
    id: "routes/companies.$id.customers";
    page: "/companies/:id/customers";
  };
  "routes/companies.$id.leistungen.tsx": {
    id: "routes/companies.$id.leistungen";
    page: "/companies/:id/leistungen";
  };
  "routes/companies.$id.invoices.tsx": {
    id: "routes/companies.$id.invoices";
    page: "/companies/:id/invoices";
  };
  "routes/companies.$id.invoices.new.tsx": {
    id: "routes/companies.$id.invoices.new";
    page: "/companies/:id/invoices/new";
  };
  "routes/companies.$id.invoices.$invoiceId.tsx": {
    id: "routes/companies.$id.invoices.$invoiceId";
    page: "/companies/:id/invoices/:invoiceId";
  };
  "routes/companies.$id.invoices.$invoiceId.edit.tsx": {
    id: "routes/companies.$id.invoices.$invoiceId.edit";
    page: "/companies/:id/invoices/:invoiceId/edit";
  };
  "routes/companies.$id.reports.tsx": {
    id: "routes/companies.$id.reports";
    page: "/companies/:id/reports";
  };
  "routes/archiv.tsx": {
    id: "routes/archiv";
    page: "/archiv";
  };
  "routes/settings.password.tsx": {
    id: "routes/settings.password";
    page: "/settings/password";
  };
  "routes/admin-layout.tsx": {
    id: "routes/admin-layout";
    page: "/admin/users" | "/admin/users/new" | "/admin/users/:id" | "/admin/logs";
  };
  "routes/admin.users.tsx": {
    id: "routes/admin.users";
    page: "/admin/users";
  };
  "routes/admin.users.new.tsx": {
    id: "routes/admin.users.new";
    page: "/admin/users/new";
  };
  "routes/admin.users.$id.tsx": {
    id: "routes/admin.users.$id";
    page: "/admin/users/:id";
  };
  "routes/admin.logs.tsx": {
    id: "routes/admin.logs";
    page: "/admin/logs";
  };
  "routes/api.companies.ts": {
    id: "routes/api.companies";
    page: "/api/companies";
  };
  "routes/api.companies.$id.ts": {
    id: "routes/api.companies.$id";
    page: "/api/companies/:id";
  };
  "routes/api.companies.$id.customers.ts": {
    id: "routes/api.companies.$id.customers";
    page: "/api/companies/:id/customers";
  };
  "routes/api.companies.$id.invoices.ts": {
    id: "routes/api.companies.$id.invoices";
    page: "/api/companies/:id/invoices";
  };
  "routes/api.customers.ts": {
    id: "routes/api.customers";
    page: "/api/customers";
  };
  "routes/api.customers.$id.ts": {
    id: "routes/api.customers.$id";
    page: "/api/customers/:id";
  };
  "routes/api.services.ts": {
    id: "routes/api.services";
    page: "/api/services";
  };
  "routes/api.services.$id.ts": {
    id: "routes/api.services.$id";
    page: "/api/services/:id";
  };
  "routes/api.invoices.ts": {
    id: "routes/api.invoices";
    page: "/api/invoices";
  };
  "routes/api.invoices.$id.ts": {
    id: "routes/api.invoices.$id";
    page: "/api/invoices/:id";
  };
  "routes/api.invoices.$id.pdf.ts": {
    id: "routes/api.invoices.$id.pdf";
    page: "/api/invoices/:id/pdf";
  };
  "routes/api.invoices.$id.xml.ts": {
    id: "routes/api.invoices.$id.xml";
    page: "/api/invoices/:id/xml";
  };
  "routes/api.reports.ts": {
    id: "routes/api.reports";
    page: "/api/reports";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/logout": typeof import("./app/routes/logout.ts");
  "routes/dashboard-layout": typeof import("./app/routes/dashboard-layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/companies": typeof import("./app/routes/companies.tsx");
  "routes/companies.new": typeof import("./app/routes/companies.new.tsx");
  "routes/companies.$id": typeof import("./app/routes/companies.$id.tsx");
  "routes/companies.$id.edit": typeof import("./app/routes/companies.$id.edit.tsx");
  "routes/companies.$id.customers": typeof import("./app/routes/companies.$id.customers.tsx");
  "routes/companies.$id.leistungen": typeof import("./app/routes/companies.$id.leistungen.tsx");
  "routes/companies.$id.invoices": typeof import("./app/routes/companies.$id.invoices.tsx");
  "routes/companies.$id.invoices.new": typeof import("./app/routes/companies.$id.invoices.new.tsx");
  "routes/companies.$id.invoices.$invoiceId": typeof import("./app/routes/companies.$id.invoices.$invoiceId.tsx");
  "routes/companies.$id.invoices.$invoiceId.edit": typeof import("./app/routes/companies.$id.invoices.$invoiceId.edit.tsx");
  "routes/companies.$id.reports": typeof import("./app/routes/companies.$id.reports.tsx");
  "routes/archiv": typeof import("./app/routes/archiv.tsx");
  "routes/settings.password": typeof import("./app/routes/settings.password.tsx");
  "routes/admin-layout": typeof import("./app/routes/admin-layout.tsx");
  "routes/admin.users": typeof import("./app/routes/admin.users.tsx");
  "routes/admin.users.new": typeof import("./app/routes/admin.users.new.tsx");
  "routes/admin.users.$id": typeof import("./app/routes/admin.users.$id.tsx");
  "routes/admin.logs": typeof import("./app/routes/admin.logs.tsx");
  "routes/api.companies": typeof import("./app/routes/api.companies.ts");
  "routes/api.companies.$id": typeof import("./app/routes/api.companies.$id.ts");
  "routes/api.companies.$id.customers": typeof import("./app/routes/api.companies.$id.customers.ts");
  "routes/api.companies.$id.invoices": typeof import("./app/routes/api.companies.$id.invoices.ts");
  "routes/api.customers": typeof import("./app/routes/api.customers.ts");
  "routes/api.customers.$id": typeof import("./app/routes/api.customers.$id.ts");
  "routes/api.services": typeof import("./app/routes/api.services.ts");
  "routes/api.services.$id": typeof import("./app/routes/api.services.$id.ts");
  "routes/api.invoices": typeof import("./app/routes/api.invoices.ts");
  "routes/api.invoices.$id": typeof import("./app/routes/api.invoices.$id.ts");
  "routes/api.invoices.$id.pdf": typeof import("./app/routes/api.invoices.$id.pdf.ts");
  "routes/api.invoices.$id.xml": typeof import("./app/routes/api.invoices.$id.xml.ts");
  "routes/api.reports": typeof import("./app/routes/api.reports.ts");
};