-- AlterTable
ALTER TABLE `betriebseinnahmen` MODIFY `kategorie` ENUM('FUSSPFLEGE', 'PRIVATEINLAGEN', 'DARLEHEN', 'STEUERERSTATTUNGEN', 'VERSICHERUNGSERSTATTUNGEN', 'ZINSERTRAEGE', 'VERMIETUNG_VERPACHTUNG', 'VERAEUSSERUNGSERLOES', 'EIGENVERBRAUCH', 'SONSTIGE_EINNAHMEN') NOT NULL;
